# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
resources:
  pipelines:
  - pipeline: 'build'   # Name of the pipeline resource
    source: 'Build' # Name of the triggering pipeline
    trigger: 
      branches:
      - develop
      - releases/*
      - master

variables:
- name: _registryName
  value: 'aksdemodeploy'
- name: _chart
  value: '$(_registryName)/mypythonapp'
- name: _release
  value: 'mypythonapp'
- name: _version
  value: '$(resources.pipeline.build.runId)'
  
stages:
- stage: Deploy
  displayName: Deploy on Kubernetes
  jobs:  
  - job: Deploy
    displayName: Deploy on Kubernetes
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      displayName: 'Helm Install'
      inputs:
        helmVersionToInstall: '3.2.1'
    - task: AzureCLI@1
      displayName: 'Azure CLI - Add Helm Repo'
      inputs:
        azureSubscription: 'padasil-internal(d715d5e4-d389-48cd-8418-8514bea2a27e)'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr helm repo add --name $(_registryName)'
    - task: HelmDeploy@0
      displayName: "Helm Deploy"
      timeoutInMinutes: 2
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'kubernetesconnection'
        namespace: 'default'
        command: 'upgrade'
        chartType: 'Name'
        chartName: '$(_chart)'
        releaseName: '$(_release)'
        overrideValues: 'image.tag=$(_version)'
        arguments: '--version="$(_version)"'